//! Lowering pass: Moon AST → C# IR.

use crate::ast::*;
use crate::lexer::token::Span;
use super::csharp_ir::*;

/// Lower a Moon file to C# IR.
pub fn lower_file(file: &File) -> CsFile {
    let usings = lower_usings(&file.usings);
    let (class, extra_types) = lower_decl(&file.decl);

    CsFile {
        header_comment: "// <auto-generated>\n// This file was generated by the Moon compiler. Do not edit manually.\n// </auto-generated>".into(),
        usings,
        class,
        extra_types,
    }
}

fn lower_usings(usings: &[UsingDecl]) -> Vec<String> {
    let mut result: Vec<String> = usings.iter().map(|u| u.path.clone()).collect();
    // Ensure System.Collections is present (for IEnumerator)
    if !result.iter().any(|u| u == "System.Collections") {
        result.push("System.Collections".into());
    }
    result
}

fn lower_decl(decl: &Decl) -> (CsClass, Vec<CsClass>) {
    match decl {
        Decl::Component { name, base_class, interfaces, members, .. } => {
            let mut cs_members = Vec::new();
            let (require_fields, optional_fields, child_fields, parent_fields, user_awake) =
                collect_component_init(members);

            // Lower fields first
            for m in members {
                match m {
                    Member::SerializeField { .. } | Member::Field { .. } => {
                        cs_members.extend(lower_field_member(m));
                    }
                    Member::Require { name, ty, .. }
                    | Member::Optional { name, ty, .. }
                    | Member::Child { name, ty, .. }
                    | Member::Parent { name, ty, .. } => {
                        let cs_ty = lower_type(ty);
                        let backing = format!("_{}", name);
                        cs_members.push(CsMember::Field {
                            attributes: vec![],
                            modifiers: "private".into(),
                            ty: cs_ty.clone(),
                            name: backing.clone(),
                            init: None,
                        });
                        cs_members.push(CsMember::Property {
                            modifiers: "public".into(),
                            ty: cs_ty,
                            name: name.clone(),
                            getter_expr: backing,
                            setter: None,
                            setter_expr: None,
                        });
                    }
                    _ => {}
                }
            }

            // Generate Awake method (require/optional resolution + user awake)
            if !require_fields.is_empty() || !optional_fields.is_empty()
                || !child_fields.is_empty() || !parent_fields.is_empty()
                || user_awake.is_some()
            {
                cs_members.push(lower_awake(
                    name, &require_fields, &optional_fields,
                    &child_fields, &parent_fields, user_awake,
                ));
            }

            // Lower remaining members
            for m in members {
                match m {
                    Member::Lifecycle { kind, params, body, .. } if *kind != LifecycleKind::Awake => {
                        cs_members.push(lower_lifecycle(*kind, params, body));
                    }
                    Member::Func { .. } => {
                        cs_members.push(lower_func_member(m));
                    }
                    Member::Coroutine { name: cname, params, body, .. } => {
                        cs_members.push(lower_coroutine(cname, params, body));
                    }
                    Member::IntrinsicFunc { visibility, name: fname, params, return_ty, code, .. } => {
                        let ret = return_ty.as_ref().map(|t| lower_type(t)).unwrap_or("void".into());
                        let ps: Vec<CsParam> = params.iter().map(|p| CsParam {
                            ty: lower_type(&p.ty), name: p.name.clone(), default: None,
                        }).collect();
                        cs_members.push(CsMember::Method {
                            attributes: vec![],
                            modifiers: format!("{} {}", lower_visibility(*visibility), "").trim().to_string(),
                            return_ty: ret,
                            name: fname.clone(),
                            params: ps,
                            body: vec![CsStmt::Raw(code.clone(), None)],
                            source_span: None,
                        });
                    }
                    _ => {}
                }
            }

            if needs_expr_helper(&cs_members) {
                cs_members.push(lower_expr_helper_member());
            }

            (
                CsClass {
                    attributes: vec![],
                    modifiers: "public".into(),
                    name: name.clone(),
                    base_class: Some(base_class.clone()),
                    interfaces: interfaces.clone(),
                    members: cs_members,
                },
                vec![],
            )
        }
        Decl::Asset { name, base_class, members, .. } => {
            let mut cs_members = Vec::new();
            for m in members {
                match m {
                    Member::SerializeField { .. } | Member::Field { .. } => {
                        cs_members.extend(lower_field_member(m));
                    }
                    Member::Func { .. } => {
                        cs_members.push(lower_func_member(m));
                    }
                    _ => {}
                }
            }
            if needs_expr_helper(&cs_members) {
                cs_members.push(lower_expr_helper_member());
            }
            (
                CsClass {
                    attributes: vec![format!("[CreateAssetMenu(fileName = \"New {name}\", menuName = \"Moon/{name}\")]")],
                    modifiers: "public".into(),
                    name: name.clone(),
                    base_class: Some(base_class.clone()),
                    interfaces: vec![],
                    members: cs_members,
                },
                vec![],
            )
        }
        Decl::Class { name, super_class, interfaces, members, .. } => {
            let mut cs_members = Vec::new();
            for m in members {
                match m {
                    Member::Field { .. } => cs_members.extend(lower_field_member(m)),
                    Member::Func { .. } => cs_members.push(lower_func_member(m)),
                    _ => {}
                }
            }
            if needs_expr_helper(&cs_members) {
                cs_members.push(lower_expr_helper_member());
            }
            (
                CsClass {
                    attributes: vec![],
                    modifiers: "public".into(),
                    name: name.clone(),
                    base_class: super_class.clone(),
                    interfaces: interfaces.clone(),
                    members: cs_members,
                },
                vec![],
            )
        }
        Decl::DataClass { name, fields, .. } => {
            (lower_data_class(name, fields), vec![])
        }
        Decl::Enum { name, params, entries, .. } => {
            let mut cs_members = Vec::new();
            for entry in entries {
                cs_members.push(CsMember::RawCode(format!("{},", entry.name)));
            }
            let enum_class = CsClass {
                attributes: vec![],
                modifiers: "public enum".into(),
                name: name.clone(),
                base_class: None,
                interfaces: vec![],
                members: cs_members,
            };
            let extra_types = if params.is_empty() {
                vec![]
            } else {
                vec![lower_parameterized_enum_extensions(name, params, entries)]
            };
            (enum_class, extra_types)
        }
        Decl::Attribute { name, fields, targets, .. } => {
            // attribute Foo(val x: Int) : Method, Property
            // → [AttributeUsage(AttributeTargets.Method | AttributeTargets.Property)]
            //   public class FooAttribute : System.Attribute { ... }
            let mut cs_members = Vec::new();
            let mut ctor_params = Vec::new();
            let mut ctor_body = Vec::new();
            for f in fields {
                let cs_ty = lower_type(&f.ty);
                cs_members.push(CsMember::Field {
                    attributes: vec![],
                    modifiers: "public".into(),
                    ty: cs_ty.clone(),
                    name: f.name.clone(),
                    init: None,
                });
                ctor_params.push(CsParam {
                    ty: cs_ty.clone(),
                    name: f.name.clone(),
                    default: None,
                });
                ctor_body.push(CsStmt::Assignment {
                    target: format!("this.{}", f.name),
                    op: "=".into(),
                    value: f.name.clone(),
                    source_span: None,
                });
            }
            cs_members.push(CsMember::Method {
                attributes: vec![],
                modifiers: "public".into(),
                return_ty: String::new(), // constructor — no return type
                name: format!("{}Attribute", name),
                params: ctor_params,
                body: ctor_body,
                source_span: None,
            });
            let usage = if targets.is_empty() {
                "System.AttributeTargets.All".to_string()
            } else {
                targets.iter()
                    .map(|t| format!("System.AttributeTargets.{}", t))
                    .collect::<Vec<_>>()
                    .join(" | ")
            };
            (
                CsClass {
                    attributes: vec![format!("[System.AttributeUsage({})]", usage)],
                    modifiers: "public".into(),
                    name: format!("{}Attribute", name),
                    base_class: Some("System.Attribute".into()),
                    interfaces: vec![],
                    members: cs_members,
                },
                vec![],
            )
        }
    }
}

fn lower_data_class(name: &str, fields: &[Param]) -> CsClass {
    let mut cs_members = Vec::new();

    for field in fields {
        cs_members.push(CsMember::Field {
            attributes: vec![],
            modifiers: "public".into(),
            ty: lower_type(&field.ty),
            name: field.name.clone(),
            init: None,
        });
    }

    cs_members.push(lower_data_class_constructor(name, fields));
    cs_members.push(lower_data_class_equals(name, fields));
    cs_members.push(lower_data_class_hash_code(fields));
    cs_members.push(lower_data_class_to_string(name, fields));
    if needs_expr_helper(&cs_members) {
        cs_members.push(lower_expr_helper_member());
    }

    CsClass {
        attributes: vec!["[System.Serializable]".into()],
        modifiers: "public".into(),
        name: name.into(),
        base_class: None,
        interfaces: vec![],
        members: cs_members,
    }
}

fn lower_expr_helper_member() -> CsMember {
    CsMember::Method {
        attributes: vec![],
        modifiers: "private static".into(),
        return_ty: "T".into(),
        name: "__moon_expr<T>".into(),
        params: vec![CsParam {
            ty: "System.Func<T>".into(),
            name: "thunk".into(),
            default: None,
        }],
        body: vec![CsStmt::Return(Some("thunk()".into()), None)],
        source_span: None,
    }
}

/// Returns true if any member references `__moon_expr` (i.e. uses a block expression).
/// Used to conditionally emit the helper method only when needed.
fn needs_expr_helper(members: &[CsMember]) -> bool {
    members.iter().any(|m| member_uses_expr_helper(m))
}

fn member_uses_expr_helper(member: &CsMember) -> bool {
    match member {
        CsMember::Method { body, .. } => body.iter().any(|s| stmt_uses_expr_helper(s)),
        _ => false,
    }
}

fn stmt_uses_expr_helper(stmt: &CsStmt) -> bool {
    match stmt {
        CsStmt::Expr(s, _) | CsStmt::Raw(s, _) => s.contains("__moon_expr"),
        CsStmt::Return(Some(s), _) | CsStmt::YieldReturn(s, _) => s.contains("__moon_expr"),
        CsStmt::VarDecl { init, .. } => init.contains("__moon_expr"),
        CsStmt::Assignment { value, .. } => value.contains("__moon_expr"),
        CsStmt::If { cond, then_body, else_body, .. } => {
            cond.contains("__moon_expr")
                || then_body.iter().any(|s| stmt_uses_expr_helper(s))
                || else_body.as_ref().map_or(false, |b| b.iter().any(|s| stmt_uses_expr_helper(s)))
        }
        CsStmt::Switch { subject, cases, .. } => {
            subject.contains("__moon_expr")
                || cases.iter().any(|c| c.body.iter().any(|s| stmt_uses_expr_helper(s)))
        }
        CsStmt::For { init, cond, incr, body, .. } => {
            init.contains("__moon_expr")
                || cond.contains("__moon_expr")
                || incr.contains("__moon_expr")
                || body.iter().any(|s| stmt_uses_expr_helper(s))
        }
        CsStmt::ForEach { iterable, body, .. } => {
            iterable.contains("__moon_expr")
                || body.iter().any(|s| stmt_uses_expr_helper(s))
        }
        CsStmt::While { cond, body, .. } => {
            cond.contains("__moon_expr")
                || body.iter().any(|s| stmt_uses_expr_helper(s))
        }
        CsStmt::Block(stmts, _) => stmts.iter().any(|s| stmt_uses_expr_helper(s)),
        _ => false,
    }
}

fn lower_data_class_constructor(name: &str, fields: &[Param]) -> CsMember {
    let params = fields
        .iter()
        .map(|field| CsParam {
            ty: lower_type(&field.ty),
            name: field.name.clone(),
            default: None,
        })
        .collect();

    let body = fields
        .iter()
        .map(|field| CsStmt::Assignment {
            target: format!("this.{}", field.name),
            op: "=".into(),
            value: field.name.clone(),
            source_span: None,
        })
        .collect();

    CsMember::Method {
        attributes: vec![],
        modifiers: "public".into(),
        return_ty: String::new(),
        name: name.into(),
        params,
        body,
        source_span: None,
    }
}

fn lower_data_class_equals(name: &str, fields: &[Param]) -> CsMember {
    let equality_expr = if fields.is_empty() {
        "true".into()
    } else {
        fields
            .iter()
            .map(|field| {
                format!(
                    "System.Collections.Generic.EqualityComparer<{}>.Default.Equals({}, other.{})",
                    lower_type(&field.ty),
                    field.name,
                    field.name,
                )
            })
            .collect::<Vec<_>>()
            .join(" && ")
    };

    CsMember::Method {
        attributes: vec![],
        modifiers: "public override".into(),
        return_ty: "bool".into(),
        name: "Equals".into(),
        params: vec![CsParam {
            ty: "object".into(),
            name: "obj".into(),
            default: None,
        }],
        body: vec![
            CsStmt::If {
                cond: "ReferenceEquals(null, obj)".into(),
                then_body: vec![CsStmt::Return(Some("false".into()), None)],
                else_body: None,
                source_span: None,
            },
            CsStmt::If {
                cond: "ReferenceEquals(this, obj)".into(),
                then_body: vec![CsStmt::Return(Some("true".into()), None)],
                else_body: None,
                source_span: None,
            },
            CsStmt::If {
                cond: "obj.GetType() != GetType()".into(),
                then_body: vec![CsStmt::Return(Some("false".into()), None)],
                else_body: None,
                source_span: None,
            },
            CsStmt::VarDecl {
                ty: "var".into(),
                name: "other".into(),
                init: format!("({})obj", name),
                source_span: None,
            },
            CsStmt::Return(Some(equality_expr), None),
        ],
        source_span: None,
    }
}

fn lower_data_class_hash_code(fields: &[Param]) -> CsMember {
    let body = if fields.is_empty() {
        vec![CsStmt::Return(Some("17".into()), None)]
    } else {
        let mut lines = vec![
            "unchecked".to_string(),
            "{".to_string(),
            "    var hash = 17;".to_string(),
        ];
        for field in fields {
            lines.push(format!(
                "    hash = (hash * 31) + System.Collections.Generic.EqualityComparer<{}>.Default.GetHashCode({});",
                lower_type(&field.ty),
                field.name,
            ));
        }
        lines.push("    return hash;".to_string());
        lines.push("}".to_string());
        vec![CsStmt::Raw(lines.join("\n"), None)]
    };

    CsMember::Method {
        attributes: vec![],
        modifiers: "public override".into(),
        return_ty: "int".into(),
        name: "GetHashCode".into(),
        params: vec![],
        body,
        source_span: None,
    }
}

fn lower_data_class_to_string(name: &str, fields: &[Param]) -> CsMember {
    let body_expr = if fields.is_empty() {
        format!("$\"{}()\"", name)
    } else {
        let fields_display = fields
            .iter()
            .map(|field| format!("{}={{{}}}", field.name, field.name))
            .collect::<Vec<_>>()
            .join(", ");
        format!("$\"{}({})\"", name, fields_display)
    };

    CsMember::Method {
        attributes: vec![],
        modifiers: "public override".into(),
        return_ty: "string".into(),
        name: "ToString".into(),
        params: vec![],
        body: vec![CsStmt::Return(Some(body_expr), None)],
        source_span: None,
    }
}

fn lower_parameterized_enum_extensions(name: &str, params: &[EnumParam], entries: &[EnumEntry]) -> CsClass {
    let mut members = Vec::new();

    for (index, param) in params.iter().enumerate() {
        let mut cases = Vec::new();
        for entry in entries {
            cases.push(CsSwitchCase {
                pattern: format!("case {}.{}:", name, entry.name),
                body: vec![CsStmt::Return(Some(
                    entry
                        .args
                        .get(index)
                        .map(lower_expr)
                        .unwrap_or_else(|| "default".into()),
                ), None)],
            });
        }
        cases.push(CsSwitchCase {
            pattern: "default:".into(),
            body: vec![CsStmt::Raw(format!(
                "throw new System.InvalidOperationException($\"Unknown {} value: {{value}}\");",
                name,
            ), None)],
        });

        members.push(CsMember::Method {
            attributes: vec![],
            modifiers: "public static".into(),
            return_ty: lower_type(&param.ty),
            name: pascal_case(&param.name),
            params: vec![CsParam {
                ty: format!("this {}", name),
                name: "value".into(),
                default: None,
            }],
            body: vec![CsStmt::Switch {
                subject: "value".into(),
                cases,
                source_span: None,
            }],
            source_span: None,
        });
    }

    CsClass {
        attributes: vec![],
        modifiers: "public static".into(),
        name: format!("{}Extensions", name),
        base_class: None,
        interfaces: vec![],
        members,
    }
}

// ── Field lowering ──────────────────────────────────────────────

/// Check if annotations contain @field
fn has_field_annotation(annotations: &[Annotation]) -> bool {
    annotations.iter().any(|a| a.name == "field")
}

fn lower_field_member(m: &Member) -> Vec<CsMember> {
    match m {
        Member::SerializeField { annotations, visibility, mutability, name, ty, init, .. } => {
            let cs_ty = lower_type(ty);
            let init_str = init.as_ref().map(|e| lower_expr(e));
            let getter_vis = match visibility {
                Some(v) => lower_visibility(*v),
                None => "public".into(),
            };

            // @field → direct public field, no backing+property
            if has_field_annotation(annotations) {
                let mut attrs = vec!["[SerializeField]".into()];
                for ann in annotations {
                    if ann.name != "field" {
                        attrs.push(lower_annotation(ann));
                    }
                }
                return vec![CsMember::Field {
                    attributes: attrs,
                    modifiers: getter_vis,
                    ty: cs_ty,
                    name: name.clone(),
                    init: init_str,
                }];
            }

            let backing = format!("_{}", name);
            let mut attrs = vec!["[SerializeField]".into()];
            for ann in annotations {
                attrs.push(lower_annotation(ann));
            }

            let mut result = vec![
                CsMember::Field {
                    attributes: attrs,
                    modifiers: "private".into(),
                    ty: cs_ty.clone(),
                    name: backing.clone(),
                    init: init_str,
                },
            ];

            match mutability {
                Mutability::Var => {
                    result.push(CsMember::Property {
                        modifiers: getter_vis,
                        ty: cs_ty,
                        name: name.clone(),
                        getter_expr: backing.clone(),
                        setter: Some("set".into()),
                        setter_expr: Some(backing),
                    });
                }
                _ => {
                    result.push(CsMember::Property {
                        modifiers: getter_vis,
                        ty: cs_ty,
                        name: name.clone(),
                        getter_expr: backing,
                        setter: None,
                        setter_expr: None,
                    });
                }
            }
            result
        }
        Member::Field { visibility, mutability, name, ty, init, .. } => {
            let cs_ty = ty.as_ref().map(|t| lower_type(t)).unwrap_or("var".into());
            let init_str = init.as_ref().map(|e| lower_expr(e));

            // const → C# const (no backing field pattern)
            if *mutability == Mutability::Const {
                let vis = lower_visibility(*visibility);
                return vec![CsMember::Field {
                    attributes: vec![],
                    modifiers: format!("{} const", vis),
                    ty: cs_ty,
                    name: name.clone(),
                    init: init_str,
                }];
            }

            let backing = format!("_{}", name);
            let getter_vis = lower_visibility(*visibility);

            let mut result = vec![
                CsMember::Field {
                    attributes: vec![],
                    modifiers: "private".into(),
                    ty: cs_ty.clone(),
                    name: backing.clone(),
                    init: init_str,
                },
            ];

            match mutability {
                Mutability::Var => {
                    result.push(CsMember::Property {
                        modifiers: getter_vis,
                        ty: cs_ty,
                        name: name.clone(),
                        getter_expr: backing.clone(),
                        setter: Some("set".into()),
                        setter_expr: Some(backing),
                    });
                }
                _ => {
                    result.push(CsMember::Property {
                        modifiers: getter_vis,
                        ty: cs_ty,
                        name: name.clone(),
                        getter_expr: backing,
                        setter: None,
                        setter_expr: None,
                    });
                }
            }
            result
        }
        _ => vec![],
    }
}

// ── Awake assembly ──────────────────────────────────────────────

struct FieldInfo {
    name: String,
    ty_str: String,
}

fn collect_component_init(members: &[Member]) -> (Vec<FieldInfo>, Vec<FieldInfo>, Vec<FieldInfo>, Vec<FieldInfo>, Option<&Block>) {
    let mut require = Vec::new();
    let mut optional = Vec::new();
    let mut child = Vec::new();
    let mut parent = Vec::new();
    let mut user_awake = None;

    for m in members {
        match m {
            Member::Require { name, ty, .. } => {
                require.push(FieldInfo { name: name.clone(), ty_str: lower_type(ty) });
            }
            Member::Optional { name, ty, .. } => {
                optional.push(FieldInfo { name: name.clone(), ty_str: lower_type(ty) });
            }
            Member::Child { name, ty, .. } => {
                child.push(FieldInfo { name: name.clone(), ty_str: lower_type(ty) });
            }
            Member::Parent { name, ty, .. } => {
                parent.push(FieldInfo { name: name.clone(), ty_str: lower_type(ty) });
            }
            Member::Lifecycle { kind: LifecycleKind::Awake, body, .. } => {
                user_awake = Some(body);
            }
            _ => {}
        }
    }
    (require, optional, child, parent, user_awake)
}

fn lower_awake(
    component_name: &str,
    require: &[FieldInfo],
    optional: &[FieldInfo],
    child: &[FieldInfo],
    parent: &[FieldInfo],
    user_awake: Option<&Block>,
) -> CsMember {
    let mut body = Vec::new();

    // Require fields
    for f in require {
        let backing = format!("_{}", f.name);
        body.push(CsStmt::Assignment {
            target: backing.clone(),
            op: "=".into(),
            value: format!("GetComponent<{}>()", f.ty_str),
            source_span: None,
        });
        body.push(CsStmt::If {
            cond: format!("{} == null", backing),
            then_body: vec![
                CsStmt::Expr(format!(
                    "Debug.LogError($\"[{}] Required component {} not found on {{gameObject.name}}\", this)",
                    component_name, f.ty_str
                ), None),
                CsStmt::Assignment { target: "enabled".into(), op: "=".into(), value: "false".into(), source_span: None },
                CsStmt::Return(None, None),
            ],
            else_body: None,
            source_span: None,
        });
    }

    // Optional fields
    for f in optional {
        body.push(CsStmt::Assignment {
            target: format!("_{}", f.name),
            op: "=".into(),
            value: format!("GetComponent<{}>()", f.ty_str),
            source_span: None,
        });
    }

    // Child fields
    for f in child {
        let backing = format!("_{}", f.name);
        body.push(CsStmt::Assignment {
            target: backing.clone(),
            op: "=".into(),
            value: format!("GetComponentInChildren<{}>()", f.ty_str),
            source_span: None,
        });
        body.push(CsStmt::If {
            cond: format!("{} == null", backing),
            then_body: vec![
                CsStmt::Expr(format!(
                    "Debug.LogError($\"[{}] Required child component {} not found on {{gameObject.name}}\", this)",
                    component_name, f.ty_str
                ), None),
                CsStmt::Assignment { target: "enabled".into(), op: "=".into(), value: "false".into(), source_span: None },
                CsStmt::Return(None, None),
            ],
            else_body: None,
            source_span: None,
        });
    }

    // Parent fields
    for f in parent {
        let backing = format!("_{}", f.name);
        body.push(CsStmt::Assignment {
            target: backing.clone(),
            op: "=".into(),
            value: format!("GetComponentInParent<{}>()", f.ty_str),
            source_span: None,
        });
        body.push(CsStmt::If {
            cond: format!("{} == null", backing),
            then_body: vec![
                CsStmt::Expr(format!(
                    "Debug.LogError($\"[{}] Required parent component {} not found on {{gameObject.name}}\", this)",
                    component_name, f.ty_str
                ), None),
                CsStmt::Assignment { target: "enabled".into(), op: "=".into(), value: "false".into(), source_span: None },
                CsStmt::Return(None, None),
            ],
            else_body: None,
            source_span: None,
        });
    }

    // User awake block
    if let Some(awake_block) = user_awake {
        for stmt in &awake_block.stmts {
            body.push(lower_stmt(stmt));
        }
    }

    CsMember::Method {
        attributes: vec![],
        modifiers: "private".into(),
        return_ty: "void".into(),
        name: "Awake".into(),
        params: vec![],
        body,
        source_span: None,
    }
}

// ── Lifecycle lowering ──────────────────────────────────────────

fn lower_lifecycle(kind: LifecycleKind, params: &[Param], body_block: &Block) -> CsMember {
    let method_name = match kind {
        LifecycleKind::Start => "Start",
        LifecycleKind::Update => "Update",
        LifecycleKind::FixedUpdate => "FixedUpdate",
        LifecycleKind::LateUpdate => "LateUpdate",
        LifecycleKind::OnEnable => "OnEnable",
        LifecycleKind::OnDisable => "OnDisable",
        LifecycleKind::OnDestroy => "OnDestroy",
        LifecycleKind::OnTriggerEnter => "OnTriggerEnter",
        LifecycleKind::OnTriggerExit => "OnTriggerExit",
        LifecycleKind::OnTriggerStay => "OnTriggerStay",
        LifecycleKind::OnCollisionEnter => "OnCollisionEnter",
        LifecycleKind::OnCollisionExit => "OnCollisionExit",
        LifecycleKind::OnCollisionStay => "OnCollisionStay",
        LifecycleKind::Awake => "Awake", // shouldn't happen here
    };

    let cs_params: Vec<CsParam> = params.iter().map(|p| CsParam {
        ty: lower_type(&p.ty),
        name: p.name.clone(),
        default: None,
    }).collect();

    let body: Vec<CsStmt> = body_block.stmts.iter().map(|s| lower_stmt(s)).collect();

    CsMember::Method {
        attributes: vec![],
        modifiers: "private".into(),
        return_ty: "void".into(),
        name: method_name.into(),
        params: cs_params,
        body,
        source_span: Some(body_block.span),
    }
}

// ── Function lowering ───────────────────────────────────────────

fn lower_func_member(m: &Member) -> CsMember {
    match m {
        Member::Func { visibility, is_override, name, params, return_ty, body, .. } => {
            let ret = return_ty.as_ref().map(|t| lower_type(t)).unwrap_or("void".into());
            let ps: Vec<CsParam> = params.iter().map(|p| CsParam {
                ty: lower_type(&p.ty), name: p.name.clone(), default: None,
            }).collect();

            let mut mods = lower_visibility(*visibility);
            if *is_override {
                mods = format!("{} override", mods);
            }

            let cs_body = match body {
                FuncBody::Block(block) => {
                    block.stmts.iter().map(|s| lower_stmt(s)).collect()
                }
                FuncBody::ExprBody(expr) => {
                    vec![CsStmt::Return(Some(lower_expr(expr)), Some(expr_span(expr)))]
                }
            };

            CsMember::Method {
                attributes: vec![],
                modifiers: mods,
                return_ty: ret,
                name: name.clone(),
                params: ps,
                body: cs_body,
                source_span: Some(member_span(m)),
            }
        }
        _ => CsMember::RawCode("// unexpected member".into()),
    }
}

// ── Coroutine lowering ──────────────────────────────────────────

fn lower_coroutine(name: &str, params: &[Param], body: &Block) -> CsMember {
    let ps: Vec<CsParam> = params.iter().map(|p| CsParam {
        ty: lower_type(&p.ty), name: p.name.clone(), default: None,
    }).collect();

    let cs_body: Vec<CsStmt> = body.stmts.iter().map(|s| lower_stmt(s)).collect();

    CsMember::Method {
        attributes: vec![],
        modifiers: "private".into(),
        return_ty: "System.Collections.IEnumerator".into(),
        name: name.into(),
        params: ps,
        body: cs_body,
        source_span: Some(body.span),
    }
}

// ── Statement lowering ──────────────────────────────────────────

fn stmt_span(stmt: &Stmt) -> Span {
    match stmt {
        Stmt::ValDecl { span, .. }
        | Stmt::VarDecl { span, .. }
        | Stmt::Assignment { span, .. }
        | Stmt::Expr { span, .. }
        | Stmt::If { span, .. }
        | Stmt::When { span, .. }
        | Stmt::For { span, .. }
        | Stmt::While { span, .. }
        | Stmt::Return { span, .. }
        | Stmt::Wait { span, .. }
        | Stmt::Start { span, .. }
        | Stmt::Stop { span, .. }
        | Stmt::StopAll { span, .. }
        | Stmt::Listen { span, .. }
        | Stmt::IntrinsicBlock { span, .. }
        | Stmt::Break { span, .. }
        | Stmt::Continue { span, .. } => *span,
    }
}

fn expr_span(expr: &Expr) -> Span {
    match expr {
        Expr::IntLit(_, span)
        | Expr::FloatLit(_, span)
        | Expr::DurationLit(_, span)
        | Expr::StringLit(_, span)
        | Expr::BoolLit(_, span)
        | Expr::Null(span)
        | Expr::Ident(_, span)
        | Expr::This(span) => *span,
        Expr::StringInterp { span, .. }
        | Expr::Binary { span, .. }
        | Expr::Unary { span, .. }
        | Expr::MemberAccess { span, .. }
        | Expr::SafeCall { span, .. }
        | Expr::SafeMethodCall { span, .. }
        | Expr::NonNullAssert { span, .. }
        | Expr::Elvis { span, .. }
        | Expr::Call { span, .. }
        | Expr::IndexAccess { span, .. }
        | Expr::IfExpr { span, .. }
        | Expr::WhenExpr { span, .. }
        | Expr::Range { span, .. }
        | Expr::Is { span, .. }
        | Expr::Lambda { span, .. }
        | Expr::IntrinsicExpr { span, .. } => *span,
    }
}

fn member_span(member: &Member) -> Span {
    match member {
        Member::SerializeField { span, .. }
        | Member::Field { span, .. }
        | Member::Require { span, .. }
        | Member::Optional { span, .. }
        | Member::Child { span, .. }
        | Member::Parent { span, .. }
        | Member::Func { span, .. }
        | Member::Coroutine { span, .. }
        | Member::Lifecycle { span, .. }
        | Member::IntrinsicFunc { span, .. }
        | Member::IntrinsicCoroutine { span, .. } => *span,
    }
}

fn lower_stmt(stmt: &Stmt) -> CsStmt {
    let source_span = Some(stmt_span(stmt));
    match stmt {
        Stmt::ValDecl { name, ty, init, .. } => {
            let cs_ty = ty.as_ref().map(|t| lower_type(t)).unwrap_or("var".into());
            CsStmt::VarDecl { ty: cs_ty, name: name.clone(), init: lower_expr(init), source_span }
        }
        Stmt::VarDecl { name, ty, init, .. } => {
            let cs_ty = ty.as_ref().map(|t| lower_type(t)).unwrap_or("var".into());
            let init_str = init.as_ref().map(|e| lower_expr(e)).unwrap_or("default".into());
            CsStmt::VarDecl { ty: cs_ty, name: name.clone(), init: init_str, source_span }
        }
        Stmt::Assignment { target, op, value, .. } => {
            let op_str = match op {
                AssignOp::Assign => "=",
                AssignOp::PlusAssign => "+=",
                AssignOp::MinusAssign => "-=",
                AssignOp::StarAssign => "*=",
                AssignOp::SlashAssign => "/=",
                AssignOp::ModAssign => "%=",
            };
            CsStmt::Assignment {
                target: lower_expr(target),
                op: op_str.into(),
                value: lower_expr(value),
                source_span,
            }
        }
        Stmt::Expr { expr, .. } => {
            // Special handling for SafeMethodCall in statement context
            // Use Unity-safe null check: if (x != null) x.Method()
            if let Expr::SafeMethodCall { receiver, name, type_args, args, .. } = expr {
                let recv = lower_expr(receiver);
                let args_str: Vec<String> = args.iter().map(|a| lower_expr(&a.value)).collect();
                let ta_str = if type_args.is_empty() {
                    String::new()
                } else {
                    format!("<{}>", type_args.iter().map(|t| lower_type(t)).collect::<Vec<_>>().join(", "))
                };
                let method = pascal_case(name);
                return CsStmt::If {
                    cond: format!("{} != null", recv),
                    then_body: vec![CsStmt::Expr(format!("{}.{}{}({})", recv, method, ta_str, args_str.join(", ")), source_span)],
                    else_body: None,
                    source_span,
                };
            }
            CsStmt::Expr(lower_expr(expr), source_span)
        }
        Stmt::If { cond, then_block, else_branch, .. } => {
            let else_body = else_branch.as_ref().map(|eb| match eb {
                ElseBranch::ElseBlock(block) => {
                    block.stmts.iter().map(|s| lower_stmt(s)).collect()
                }
                ElseBranch::ElseIf(if_stmt) => {
                    vec![lower_stmt(if_stmt)]
                }
            });
            CsStmt::If {
                cond: lower_expr(cond),
                then_body: then_block.stmts.iter().map(|s| lower_stmt(s)).collect(),
                else_body,
                source_span,
            }
        }
        Stmt::When { subject, branches, .. } => {
            if let Some(subj) = subject {
                let mut cases = Vec::new();
                for b in branches {
                    let pattern = match &b.pattern {
                        WhenPattern::Expression(expr) => format!("case {}:", lower_expr(expr)),
                        WhenPattern::Is(ty) => format!("case {} _:", lower_type(ty)),
                        WhenPattern::Else => "default:".into(),
                    };
                    let mut body: Vec<CsStmt> = match &b.body {
                        WhenBody::Block(bl) => bl.stmts.iter().map(|s| lower_stmt(s)).collect(),
                        WhenBody::Expr(e) => vec![CsStmt::Expr(lower_expr(e), Some(expr_span(e)))],
                    };
                    body.push(CsStmt::Break(Some(b.span)));
                    cases.push(CsSwitchCase { pattern, body });
                }
                CsStmt::Switch { subject: lower_expr(subj), cases, source_span }
            } else {
                // Condition-based when → if/else chain
                let mut result: Option<CsStmt> = None;
                for b in branches.iter().rev() {
                    let body: Vec<CsStmt> = match &b.body {
                        WhenBody::Block(bl) => bl.stmts.iter().map(|s| lower_stmt(s)).collect(),
                        WhenBody::Expr(e) => vec![CsStmt::Expr(lower_expr(e), Some(expr_span(e)))],
                    };
                    match &b.pattern {
                        WhenPattern::Else => {
                            result = Some(CsStmt::Block(body, Some(b.span)));
                        }
                        WhenPattern::Expression(cond) => {
                            result = Some(CsStmt::If {
                                cond: lower_expr(cond),
                                then_body: body,
                                else_body: result.map(|r| vec![r]),
                                source_span: Some(b.span),
                            });
                        }
                        _ => {}
                    }
                }
                result.unwrap_or(CsStmt::Raw("// empty when".into(), source_span))
            }
        }
        Stmt::For { var_name, iterable, body, .. } => {
            // Check if iterable is a range expression
            if let Expr::Range { start, end, inclusive, step, .. } = iterable {
                let start_str = lower_expr(start);
                let end_str = lower_expr(end);
                let cond = if *inclusive {
                    format!("{} <= {}", var_name, end_str)
                } else {
                    format!("{} < {}", var_name, end_str)
                };
                let incr = if let Some(s) = step {
                    format!("{} += {}", var_name, lower_expr(s))
                } else {
                    format!("{}++", var_name)
                };
                CsStmt::For {
                    init: format!("int {} = {}", var_name, start_str),
                    cond,
                    incr,
                    body: body.stmts.iter().map(|s| lower_stmt(s)).collect(),
                    source_span,
                }
            } else {
                CsStmt::ForEach {
                    ty: "var".into(),
                    name: var_name.clone(),
                    iterable: lower_expr(iterable),
                    body: body.stmts.iter().map(|s| lower_stmt(s)).collect(),
                    source_span,
                }
            }
        }
        Stmt::While { cond, body, .. } => {
            CsStmt::While {
                cond: lower_expr(cond),
                body: body.stmts.iter().map(|s| lower_stmt(s)).collect(),
                source_span,
            }
        }
        Stmt::Return { value, .. } => {
            CsStmt::Return(value.as_ref().map(|e| lower_expr(e)), source_span)
        }
        Stmt::Wait { form, .. } => {
            match form {
                WaitForm::Duration(expr) => {
                    let val = lower_expr(expr);
                    CsStmt::YieldReturn(format!("new WaitForSeconds({})", val), source_span)
                }
                WaitForm::NextFrame => {
                    CsStmt::YieldReturn("null".into(), source_span)
                }
                WaitForm::FixedFrame => {
                    CsStmt::YieldReturn("new WaitForFixedUpdate()".into(), source_span)
                }
                WaitForm::Until(cond) => {
                    CsStmt::YieldReturn(format!("new WaitUntil(() => {})", lower_expr(cond)), source_span)
                }
                WaitForm::While(cond) => {
                    CsStmt::YieldReturn(format!("new WaitWhile(() => {})", lower_expr(cond)), source_span)
                }
            }
        }
        Stmt::Start { call, .. } => {
            CsStmt::Expr(format!("StartCoroutine({})", lower_expr(call)), source_span)
        }
        Stmt::Stop { target, .. } => {
            CsStmt::Expr(format!("StopCoroutine({})", lower_expr(target)), source_span)
        }
        Stmt::StopAll { .. } => {
            CsStmt::Expr("StopAllCoroutines()".into(), source_span)
        }
        Stmt::Listen { event, params, body, .. } => {
            let event_str = lower_expr(event);
            let params_str = if params.is_empty() {
                String::new()
            } else {
                format!("({})", params.join(", "))
            };
            let body_stmts: Vec<String> = body.stmts.iter()
                .map(|s| format!("    {};", stmt_to_inline(&lower_stmt(s))))
                .collect();
            let lambda_body = body_stmts.join("\n");
            CsStmt::Expr(format!(
                "{}.AddListener({} => {{\n{}\n}})",
                event_str, if params.is_empty() { "()" } else { &params_str }, lambda_body
            ), source_span)
        }
        Stmt::IntrinsicBlock { code, .. } => {
            CsStmt::Raw(code.clone(), source_span)
        }
        Stmt::Break { .. } => CsStmt::Break(source_span),
        Stmt::Continue { .. } => CsStmt::Continue(source_span),
    }
}

fn stmt_to_inline(stmt: &CsStmt) -> String {
    match stmt {
        CsStmt::Expr(e, _) => e.clone(),
        CsStmt::Return(Some(v), _) => format!("return {}", v),
        CsStmt::Return(None, _) => "return".into(),
        _ => format!("{:?}", stmt),
    }
}

fn lower_value_block_expr(block: &Block, context: &str) -> String {
    if block.stmts.len() == 1 {
        match &block.stmts[0] {
            Stmt::Expr { expr, .. } => return lower_expr(expr),
            Stmt::Return { value: Some(expr), .. } => return lower_expr(expr),
            _ => {}
        }
    }

    let mut lines = vec!["__moon_expr(() =>".to_string(), "{".to_string()];
    lines.extend(lower_value_block_lines(block, 1, context));
    lines.push("})".to_string());
    lines.join("\n")
}

fn lower_value_block_lines(block: &Block, indent: usize, context: &str) -> Vec<String> {
    let mut lines = Vec::new();
    if block.stmts.is_empty() {
        lines.push(format!("{}throw new System.InvalidOperationException(\"Moon {} branch must produce a value\");", indent_str(indent), context));
        return lines;
    }

    let last_index = block.stmts.len() - 1;
    for stmt in &block.stmts[..last_index] {
        lines.extend(cs_stmt_to_lines(&lower_stmt(stmt), indent));
    }

    match &block.stmts[last_index] {
        Stmt::Expr { expr, .. } => lines.push(format!("{}return {};", indent_str(indent), lower_expr(expr))),
        Stmt::Return { value: Some(expr), .. } => lines.push(format!("{}return {};", indent_str(indent), lower_expr(expr))),
        Stmt::Return { value: None, .. } => lines.push(format!("{}return default;", indent_str(indent))),
        other => {
            lines.extend(cs_stmt_to_lines(&lower_stmt(other), indent));
            lines.push(format!("{}throw new System.InvalidOperationException(\"Moon {} branch must end with a value\");", indent_str(indent), context));
        }
    }

    lines
}

fn cs_stmt_to_lines(stmt: &CsStmt, indent: usize) -> Vec<String> {
    let pad = indent_str(indent);
    match stmt {
        CsStmt::VarDecl { ty, name, init, .. } => vec![format!("{}{} {} = {};", pad, ty, name, init)],
        CsStmt::Assignment { target, op, value, .. } => vec![format!("{}{} {} {};", pad, target, op, value)],
        CsStmt::Expr(expr, _) => vec![format!("{}{};", pad, expr)],
        CsStmt::If { cond, then_body, else_body, .. } => {
            let mut lines = vec![format!("{}if ({})", pad, cond), format!("{}{{", pad)];
            for nested in then_body {
                lines.extend(cs_stmt_to_lines(nested, indent + 1));
            }
            lines.push(format!("{}}}", pad));
            if let Some(else_stmts) = else_body {
                lines.push(format!("{}else", pad));
                lines.push(format!("{}{{", pad));
                for nested in else_stmts {
                    lines.extend(cs_stmt_to_lines(nested, indent + 1));
                }
                lines.push(format!("{}}}", pad));
            }
            lines
        }
        CsStmt::Switch { subject, cases, .. } => {
            let mut lines = vec![format!("{}switch ({})", pad, subject), format!("{}{{", pad)];
            for case in cases {
                lines.push(format!("{}    {}", pad, case.pattern));
                for nested in &case.body {
                    lines.extend(cs_stmt_to_lines(nested, indent + 2));
                }
            }
            lines.push(format!("{}}}", pad));
            lines
        }
        CsStmt::For { init, cond, incr, body, .. } => {
            let mut lines = vec![format!("{}for ({}; {}; {})", pad, init, cond, incr), format!("{}{{", pad)];
            for nested in body {
                lines.extend(cs_stmt_to_lines(nested, indent + 1));
            }
            lines.push(format!("{}}}", pad));
            lines
        }
        CsStmt::ForEach { ty, name, iterable, body, .. } => {
            let mut lines = vec![format!("{}foreach ({} {} in {})", pad, ty, name, iterable), format!("{}{{", pad)];
            for nested in body {
                lines.extend(cs_stmt_to_lines(nested, indent + 1));
            }
            lines.push(format!("{}}}", pad));
            lines
        }
        CsStmt::While { cond, body, .. } => {
            let mut lines = vec![format!("{}while ({})", pad, cond), format!("{}{{", pad)];
            for nested in body {
                lines.extend(cs_stmt_to_lines(nested, indent + 1));
            }
            lines.push(format!("{}}}", pad));
            lines
        }
        CsStmt::Return(Some(value), _) => vec![format!("{}return {};", pad, value)],
        CsStmt::Return(None, _) => vec![format!("{}return;", pad)],
        CsStmt::YieldReturn(value, _) => vec![format!("{}yield return {};", pad, value)],
        CsStmt::Break(_) => vec![format!("{}break;", pad)],
        CsStmt::Continue(_) => vec![format!("{}continue;", pad)],
        CsStmt::Raw(code, _) => code.lines().map(|line| format!("{}{}", pad, line)).collect(),
        CsStmt::Block(stmts, _) => {
            let mut lines = Vec::new();
            for nested in stmts {
                lines.extend(cs_stmt_to_lines(nested, indent));
            }
            lines
        }
    }
}

fn indent_str(indent: usize) -> String {
    "    ".repeat(indent)
}

// ── Expression lowering ─────────────────────────────────────────

fn lower_expr(expr: &Expr) -> String {
    match expr {
        Expr::IntLit(n, _) => n.to_string(),
        Expr::FloatLit(n, _) => format_float(*n),
        Expr::DurationLit(n, _) => format_float(*n),
        Expr::StringLit(s, _) => format!("\"{}\"", s),
        Expr::StringInterp { parts, .. } => {
            let mut result = String::from("$\"");
            for part in parts {
                match part {
                    StringPart::Literal(s) => result.push_str(s),
                    StringPart::Expr(e) => {
                        result.push('{');
                        result.push_str(&lower_expr(e));
                        result.push('}');
                    }
                }
            }
            result.push('"');
            result
        }
        Expr::BoolLit(b, _) => if *b { "true" } else { "false" }.into(),
        Expr::Null(_) => "null".into(),
        Expr::Ident(name, _) => map_sugar_ident(name),
        Expr::This(_) => "this".into(),
        Expr::Binary { left, op, right, .. } => {
            let op_str = match op {
                BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
                BinOp::Div => "/", BinOp::Mod => "%",
                BinOp::Eq => "==", BinOp::NotEq => "!=",
                BinOp::Lt => "<", BinOp::Gt => ">",
                BinOp::LtEq => "<=", BinOp::GtEq => ">=",
                BinOp::And => "&&", BinOp::Or => "||",
            };
            format!("{} {} {}", lower_expr(left), op_str, lower_expr(right))
        }
        Expr::Unary { op, operand, .. } => {
            match op {
                UnaryOp::Negate => format!("-({})", lower_expr(operand)),
                UnaryOp::Not => format!("!({})", lower_expr(operand)),
            }
        }
        Expr::MemberAccess { receiver, name, .. } => {
            let recv = lower_expr(receiver);
            // Sugar mappings
            match (recv.as_str(), name.as_str()) {
                ("input", "axis") => "Input.GetAxis".into(),
                ("input", "getKey") => "Input.GetKey".into(),
                ("input", "getKeyDown") => "Input.GetKeyDown".into(),
                ("input", "getButton") => "Input.GetButton".into(),
                ("input", "getButtonDown") => "Input.GetButtonDown".into(),
                ("quat", "euler") => "Quaternion.Euler".into(),
                ("Time", "deltaTime") => "Time.deltaTime".into(),
                // Duration sugar: expr.s → just expr (seconds value)
                (_, "s") => recv.to_string(),
                _ => format!("{}.{}", recv, name),
            }
        }
        Expr::SafeCall { receiver, name, .. } => {
            let recv = lower_expr(receiver);
            format!("({} != null ? {}.{} : null)", recv, recv, pascal_case(name))
        }
        Expr::SafeMethodCall { receiver, name, type_args, args, .. } => {
            // SafeMethodCall in expression context — use null-conditional operator
            let recv = lower_expr(receiver);
            let args_str: Vec<String> = args.iter().map(|a| lower_expr(&a.value)).collect();
            let ta_str = if type_args.is_empty() {
                String::new()
            } else {
                format!("<{}>", type_args.iter().map(|t| lower_type(t)).collect::<Vec<_>>().join(", "))
            };
            let method = pascal_case(name);
            format!("{}?.{}{}({})", recv, method, ta_str, args_str.join(", "))
        }
        Expr::NonNullAssert { expr, .. } => {
            lower_expr(expr)
        }
        Expr::Elvis { left, right, .. } => {
            format!("{} ?? {}", lower_expr(left), lower_expr(right))
        }
        Expr::Call { receiver, name, type_args, args, .. } => {
            let args_str: Vec<String> = args.iter().map(|a| lower_expr(&a.value)).collect();
            let ta_str = if type_args.is_empty() {
                String::new()
            } else {
                format!("<{}>", type_args.iter().map(|t| lower_type(t)).collect::<Vec<_>>().join(", "))
            };

            if let Some(recv) = receiver {
                let recv_str = lower_expr(recv);
                // Handle safe call + method call (SafeCall node as receiver)
                if name.is_empty() {
                    format!("{}{}({})", recv_str, ta_str, args_str.join(", "))
                } else {
                    // Check for sugar: input.axis → Input.GetAxis, etc.
                    if let Some(mapped) = map_method_sugar(&recv_str, name) {
                        format!("{}{}({})", mapped, ta_str, args_str.join(", "))
                    } else {
                        // PascalCase for C# method calls
                        format!("{}.{}{}({})", recv_str, pascal_case(name), ta_str, args_str.join(", "))
                    }
                }
            } else {
                // Sugar function calls
                let mapped = map_sugar_call(name, &ta_str, &args_str);
                if let Some(m) = mapped {
                    m
                } else {
                    format!("{}{}({})", name, ta_str, args_str.join(", "))
                }
            }
        }
        Expr::IndexAccess { receiver, index, .. } => {
            format!("{}[{}]", lower_expr(receiver), lower_expr(index))
        }
        Expr::Range { start, .. } => {
            // Ranges are handled in for-loop lowering; this is a fallback
            lower_expr(start)
        }
        Expr::Is { expr, ty, .. } => {
            format!("{} is {}", lower_expr(expr), lower_type(ty))
        }
        Expr::IfExpr { cond, then_block, else_block, .. } => {
            format!(
                "({} ? {} : {})",
                lower_expr(cond),
                lower_value_block_expr(then_block, "if expression"),
                lower_value_block_expr(else_block, "if expression"),
            )
        }
        Expr::WhenExpr { subject, branches, .. } => {
            if let Some(subj) = subject {
                let mut lines = vec![format!("{} switch", lower_expr(subj)), "{".to_string()];
                for branch in branches {
                    let pattern = match &branch.pattern {
                        WhenPattern::Expression(expr) => lower_expr(expr),
                        WhenPattern::Is(ty) => format!("{} _", lower_type(ty)),
                        WhenPattern::Else => "_".into(),
                    };
                    let value = match &branch.body {
                        WhenBody::Expr(expr) => lower_expr(expr),
                        WhenBody::Block(block) => lower_value_block_expr(block, "when expression"),
                    };
                    lines.push(format!("    {} => {},", pattern, value));
                }
                if !branches.iter().any(|branch| matches!(branch.pattern, WhenPattern::Else)) {
                    lines.push("    _ => throw new System.InvalidOperationException(\"Moon when expression is not exhaustive\"),".to_string());
                }
                lines.push("}".to_string());
                lines.join("\n")
            } else {
                let mut result = "throw new System.InvalidOperationException(\"Moon when expression did not match any branch\")".to_string();
                for branch in branches.iter().rev() {
                    let value = match &branch.body {
                        WhenBody::Expr(expr) => lower_expr(expr),
                        WhenBody::Block(block) => lower_value_block_expr(block, "when expression"),
                    };
                    result = match &branch.pattern {
                        WhenPattern::Else => value,
                        WhenPattern::Expression(cond) => format!("({} ? {} : {})", lower_expr(cond), value, result),
                        WhenPattern::Is(_) => result,
                    };
                }
                result
            }
        }
        Expr::Lambda { .. } => {
            "/* lambda */".into()
        }
        Expr::IntrinsicExpr { code, .. } => code.clone(),
    }
}

// ── Sugar mappings ──────────────────────────────────────────────

fn map_sugar_ident(name: &str) -> String {
    match name {
        "input" => "Input".into(),
        _ => name.into(),
    }
}

fn map_sugar_call(name: &str, type_args: &str, args: &[String]) -> Option<String> {
    let args_str = args.join(", ");
    match name {
        "vec2" => Some(format!("new Vector2({})", args_str)),
        "vec3" => Some(format!("new Vector3({})", args_str)),
        "color" => Some(format!("new Color({})", args_str)),
        "get" => Some(format!("GetComponent{}()", type_args)),
        "require" => Some(format!("GetComponent{}()", type_args)),
        "find" => Some(format!("FindFirstObjectByType{}()", type_args)),
        "child" => Some(format!("GetComponentInChildren{}()", type_args)),
        "parent" => Some(format!("GetComponentInParent{}()", type_args)),
        "Destroy" => Some(format!("Destroy({})", args_str)),
        "log" => Some(format!("Debug.Log({})", args_str)),
        "warn" => Some(format!("Debug.LogWarning({})", args_str)),
        "error" => Some(format!("Debug.LogError({})", args_str)),
        "print" => {
            // print("msg") → Debug.Log
            // print("msg", Log) → Debug.Log
            // print("msg", Warn) → Debug.LogWarning
            // print("msg", Error) → Debug.LogError
            if args.len() >= 2 {
                let level = args[1].trim();
                let msg = &args[0];
                match level {
                    "Warn" => Some(format!("Debug.LogWarning({})", msg)),
                    "Error" => Some(format!("Debug.LogError({})", msg)),
                    _ => Some(format!("Debug.Log({})", msg)),
                }
            } else {
                Some(format!("Debug.Log({})", args_str))
            }
        }
        _ => None,
    }
}

// ── Type lowering ───────────────────────────────────────────────

fn lower_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Simple { name, nullable, .. } => {
            let cs = map_type_name(name);
            if *nullable { format!("{}?", cs) } else { cs }
        }
        TypeRef::Generic { name, type_args, nullable, .. } => {
            let args: Vec<String> = type_args.iter().map(|t| lower_type(t)).collect();
            // Array<T> → T[]
            let base = if name == "Array" && args.len() == 1 {
                format!("{}[]", args[0])
            } else {
                let cs_name = map_type_name(name);
                format!("{}<{}>", cs_name, args.join(", "))
            };
            if *nullable { format!("{}?", base) } else { base }
        }
        TypeRef::Qualified { qualifier, name, nullable, .. } => {
            let base = format!("{}.{}", qualifier, name);
            if *nullable { format!("{}?", base) } else { base }
        }
    }
}

fn map_type_name(name: &str) -> String {
    match name {
        "Int" => "int".into(),
        "Float" => "float".into(),
        "Double" => "double".into(),
        "Bool" => "bool".into(),
        "String" => "string".into(),
        "Char" => "char".into(),
        "Long" => "long".into(),
        "Byte" => "byte".into(),
        "Unit" => "void".into(),
        // Collection sugar
        "Array" => "System.Array".into(),
        "List" => "System.Collections.Generic.List".into(),
        "Map" => "System.Collections.Generic.Dictionary".into(),
        "Set" => "System.Collections.Generic.HashSet".into(),
        "Queue" => "System.Collections.Generic.Queue".into(),
        "Stack" => "System.Collections.Generic.Stack".into(),
        "Seq" => "System.Collections.Generic.IEnumerable".into(),
        _ => name.into(),
    }
}

fn lower_annotation(ann: &Annotation) -> String {
    if ann.args.is_empty() {
        format!("[{}]", capitalize(&ann.name))
    } else {
        let args: Vec<String> = ann.args.iter().map(|a| lower_expr(a)).collect();
        format!("[{}({})]", capitalize(&ann.name), args.join(", "))
    }
}

fn lower_visibility(vis: Visibility) -> String {
    match vis {
        Visibility::Public => "public".into(),
        Visibility::Private => "private".into(),
        Visibility::Protected => "protected".into(),
    }
}

fn map_method_sugar(receiver: &str, method: &str) -> Option<String> {
    match (receiver, method) {
        ("Input", "axis") | ("input", "axis") => Some("Input.GetAxis".into()),
        ("Input", "getKey") | ("input", "getKey") => Some("Input.GetKey".into()),
        ("Input", "getKeyDown") | ("input", "getKeyDown") => Some("Input.GetKeyDown".into()),
        ("Input", "getButton") | ("input", "getButton") => Some("Input.GetButton".into()),
        ("Input", "getButtonDown") | ("input", "getButtonDown") => Some("Input.GetButtonDown".into()),
        ("quat", "euler") => Some("Quaternion.Euler".into()),
        _ => None,
    }
}

/// Convert camelCase method name to PascalCase for C# Unity API.
fn pascal_case(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

fn format_float(n: f64) -> String {
    let s = n.to_string();
    if s.contains('.') {
        format!("{}f", s)
    } else {
        format!("{}.0f", s)
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
