// <auto-generated>
// This file was generated by the refraction compiler. Do not edit manually.
// </auto-generated>

using UnityEngine;
using System.Collections;

public class Coin : MonoBehaviour
{
    [SerializeField]
    private float rotateSpeed = 90.0f;
    [SerializeField]
    private int scoreValue = 10;

    private void Update()
    {
        transform.Rotate(new Vector3(0, rotateSpeed * Time.deltaTime, 0));
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            var player = other.Get<PlayerScore>();
            if (player != null)
            {
                player.AddScore(scoreValue);
            }
            Destroy(gameObject);
        }
    }
}
