// <auto-generated>
// This file was generated by the refraction compiler. Do not edit manually.
// </auto-generated>

using UnityEngine;
using System.Collections;

public enum EnemyState
{
    Idle,
    Chase,
    Attack,
    Dead,
}
