// <auto-generated>
// This file was generated by the Moon compiler. Do not edit manually.
// </auto-generated>

using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using System.Collections;

public class MainMenu : MonoBehaviour
{
    [SerializeField]
    private Button startButton;
    [SerializeField]
    private Button quitButton;

    private void Start()
    {
        startButton.onClick.AddListener(() => {
    SceneManager.LoadScene("Game");
});
        quitButton.onClick.AddListener(() => {
    Application.Quit();
});
    }
}
