// <auto-generated>
// This file was generated by the Moon compiler. Do not edit manually.
// </auto-generated>

using System.Collections;

[System.AttributeUsage(System.AttributeTargets.Method | System.AttributeTargets.Property)]
public class CooldownAttribute : System.Attribute
{
    public float duration;
    public bool resetOnHit;

    public  CooldownAttribute(float duration, bool resetOnHit)
    {
        this.duration = duration;
        this.resetOnHit = resetOnHit;
    }
}
