// <auto-generated>
// This file was generated by the Moon compiler. Do not edit manually.
// </auto-generated>

using UnityEngine;
using System.Collections;

public class PlayerController : MonoBehaviour
{
    [SerializeField]
    [Header("Movement")]
    private float speed = 5.0f;
    [SerializeField]
    private float jumpForce = 8.0f;
    private Rigidbody rb;
    private Animator animator;

    private void Awake()
    {
        rb = GetComponent<Rigidbody>();
        if (rb == null)
        {
            Debug.LogError($"[PlayerController] Required component Rigidbody not found on {gameObject.name}", this);
            enabled = false;
            return;
        }
        animator = GetComponent<Animator>();
    }

    private void Update()
    {
        var h = Input.GetAxis("Horizontal");
        var v = Input.GetAxis("Vertical");
        var move = new Vector3(h, 0, v);
        rb.velocity = move * speed;
    }

    public void jump()
    {
        rb.AddForce(new Vector3(0, jumpForce, 0));
        if (animator != null)
        {
            animator.Play("Jump");
        }
    }
}
