// <auto-generated>
// This file was generated by the refraction compiler. Do not edit manually.
// </auto-generated>

using UnityEngine;
using System.Collections;

public class PlayerHealth : MonoBehaviour
{
    [SerializeField]
    private int maxHp = 100;
    [SerializeField]
    private float invincibleTime = 1.0f;
    public int hp = 100;
    public bool invincible = false;

    public void damage(int amount)
    {
        if (invincible)
        {
            return;
        }
        hp -= amount;
        StartCoroutine(hitInvincible());
        if (hp <= 0)
        {
            die();
        }
    }

    private System.Collections.IEnumerator hitInvincible()
    {
        invincible = true;
        yield return new WaitForSeconds(invincibleTime);
        invincible = false;
    }

    public void die()
    {
        gameObject.SetActive(false);
    }
}
