// <auto-generated>
// This file was generated by the Moon compiler. Do not edit manually.
// </auto-generated>

using UnityEngine;
using System.Collections;

public class TypeTest : MonoBehaviour
{
    [SerializeField]
    private string name = "test";
    public System.Collections.Generic.List<int> items = null;
    public System.Collections.Generic.Dictionary<string, int> lookup = null;
    public System.Collections.Generic.HashSet<string> tags = null;

    public System.Collections.Generic.List<int> getItems()
    {
        return items;
    }

    public System.Collections.Generic.IEnumerable<string> getKeys()
    {
        return null;
    }
}
