// <auto-generated>
// This file was generated by the Moon compiler. Do not edit manually.
// </auto-generated>

using UnityEngine;
using System.Collections;

[CreateAssetMenu(fileName = "New WeaponData", menuName = "Moon/WeaponData")]
public class WeaponData : ScriptableObject
{
    [SerializeField]
    private string weaponName = "Unknown";
    [SerializeField]
    private int damage = 10;
    [SerializeField]
    private float attackSpeed = 1.0f;
    [SerializeField]
    private Sprite? icon;

    public float dps()
    {
        return damage / attackSpeed;
    }
}
