using System.IO;
using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;

namespace Prism.Editor
{
    /// <summary>
    /// Intercepts MonoScript double-click in Inspector.
    /// If the script was generated by PrSM, redirects to the .prsm source file.
    /// </summary>
    [InitializeOnLoad]
    public static class PrismScriptRedirector
    {
        static PrismScriptRedirector()
        {
            EditorApplication.update += CheckForScriptOpen;
        }

        private static double _lastCheck;

        private static void CheckForScriptOpen()
        {
            // Throttle to every 0.3s
            if (EditorApplication.timeSinceStartup - _lastCheck < 0.3)
                return;
            _lastCheck = EditorApplication.timeSinceStartup;

            // Nothing to do if no selection
            if (Selection.activeObject == null) return;

            // Check if a MonoScript in the generated folder was just opened
            // We detect this by checking if the active object is a MonoScript
            // from com.prsm.generated — if so, we don't need to do anything
            // here since OnOpenAsset should catch it.
        }

        /// <summary>
        /// Called by Unity's callback system. This catches ALL asset opens,
        /// including MonoScript from Inspector script field double-click.
        /// </summary>
        [OnOpenAsset(-10)] // Very high priority (negative = earlier)
        #pragma warning disable CS0618
        public static bool InterceptGeneratedScript(int instanceID, int line)
        {
            var obj = EditorUtility.InstanceIDToObject(instanceID);
        #pragma warning restore CS0618
            if (obj == null) return false;

            // Only intercept MonoScript assets
            var monoScript = obj as MonoScript;
            if (monoScript == null) return false;

            string csPath = AssetDatabase.GetAssetPath(monoScript);

            // Check if this is a PrSM-generated script
            if (!csPath.Contains("com.prsm.generated") &&
                !csPath.Contains("__Generated/PrSM"))
                return false;

            string projectRoot = PrismProjectSettings.GetProjectRoot();
            string fullGeneratedPath = Path.Combine(projectRoot, csPath);
            if (PrismSourceMap.TryResolveSourceLocation(projectRoot, fullGeneratedPath, line, out string sourcePath, out int sourceLine, out int sourceCol))
            {
                OpenInVSCode(sourcePath, sourceLine, sourceCol);
                return true;
            }

            // Find corresponding .prsm file
            string className = monoScript.name;
            string mnPath = FindMnFile(className);

            if (mnPath == null)
                return false;

            // Open the .prsm file instead
            string fullPath = Path.Combine(projectRoot, mnPath);
            OpenInVSCode(fullPath, line, 1);
            return true; // Consumed — don't open .cs
        }

        private static string FindMnFile(string className)
        {
            // Search by filename in Assets
            string[] guids = AssetDatabase.FindAssets(className);
            foreach (string guid in guids)
            {
                string p = AssetDatabase.GUIDToAssetPath(guid);
                if (PrismProjectConfig.IsPrismSourceAssetPath(p) && Path.GetFileNameWithoutExtension(p) == className)
                    return p;
            }
            return null;
        }

        private static void OpenInVSCode(string fullPath, int line, int col)
        {
            PrismEditorLauncher.OpenInEditor(fullPath, line, col);
        }
    }
}
